title: tree

author: 佳境Shmily

menus: 
  关于: /about

links:
  github: https://github.com/Shmilyqjj
  
favicon: /favicon.ico

# valine 
valine:
    # 评论
    enableComment: true 
    # 阅读量
    enableCounter: false
    # valine appID
    appID: zUyVEaHo59RUUwiPTChPEeBj-gzGzoHsz
    # valine appKey
    appKey: xIEyTcrkTuJLz6ewPbpTj8mz
    placeholder: 欢迎评论...
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2020